version: "2"
 
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
 
python:
  install:
    - requirements: source/requirements.txt
 
sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false